services:
  db:
    image: postgres:16-alpine
    container_name: pocket-finance-db
    environment:
      POSTGRES_DB: pocket_finance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pocket_finance"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  backend:
    image: maven:3.9.9-eclipse-temurin-21
    container_name: pocket-finance-backend-dev
    working_dir: /app
    command: >
      sh -c "mvn spring-boot:run"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: pocket_finance
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: cG9ja2V0LWZpbmFuY2UtZGV2LXNlY3JldC0zMi1ieXRlcy1taW5pbXVtLTEyMzQ1
      SPRING_DEVTOOLS_RESTART_POLL_INTERVAL: 2s
      SPRING_DEVTOOLS_RESTART_QUIET_PERIOD: 1s
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    volumes:
      - ./backend:/app
      - maven_cache:/root/.m2
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:8080/actuator/health | grep -q UP"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 120s
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: pocket-finance-frontend-dev
    working_dir: /app
    command: >
      sh -c "npm install --no-package-lock && npm run start -- --host 0.0.0.0 --port 4200 --poll 1000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    ports:
      - "${FRONTEND_PORT:-4200}:4200"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  maven_cache:
  frontend_node_modules:
